Models/LoginModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DestinoCertoMVC
{
    public class LoginModel
{
    [Required]
    public string Login { get; set; }
    
    [Required]
    [DataType(DataType.Password)]
    public string Senha { get; set; }
}
}

Models/PacoteViewModel.cs
using System;

namespace DestinoCertoMVC.Models
{
    public class PacoteViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Origem { get; set; }
        public string Destino { get; set; }
        public string Atrativos { get; set; }
        public DateTime Saida { get; set; }
        public DateTime Retorno { get; set; }
        public int UsuarioId { get; set; }
        public UsuarioViewModel Usuario { get; set; }
    }
}

Models/UsuarioViewModel.cs
using System;

namespace DestinoCertoMVC.Models
{
    public class UsuarioViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public DateTime DataNascimento { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DestinoCertoMVC.Data;
using DestinoCertoMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DestinoCertoMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly DCDbContext _context;

        public HomeController(DCDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult MenuUsuario()
        {
            ViewBag.Pacotes = _context.Pacotes.ToList();
            return View();
        }

        public IActionResult Vitrine()
        {
            ViewBag.Pacotes = _context.Pacotes.ToList();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DestinoCertoMVC.Data;
using DestinoCertoMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;

namespace DestinoCertoMVC.Controllers
{
    public class LoginController : Controller
    {
        private readonly DCDbContext _context;

        public LoginController(DCDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> LoginUsuarioAsync(LoginModel loginTry)
        {
            TempData["ErrorMessage"] = "";

            if (ModelState.IsValid)
            {
                var user = _context.Usuarios.FirstOrDefault(u =>
                    u.Login == loginTry.Login && u.Senha == loginTry.Senha
                );

                if (user != null)
                {
                    TempData["ErrorMessage"] = "";

                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.Name, user.Nome)
                    };

                    var claimsIdentity = new ClaimsIdentity(
                        claims,
                        CookieAuthenticationDefaults.AuthenticationScheme
                    );

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity)
                    );

                    return RedirectToAction("MenuUsuario", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/PacotesController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DestinoCertoMVC.Data;
using DestinoCertoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading;

namespace DestinoCertoMVC.Controllers
{
    public class PacotesController : Controller
    {
        private readonly DCDbContext _context;

        public PacotesController(DCDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdicionarPacote(PacoteViewModel pacote)
        {
            if (ModelState.IsValid)
            {
                // Obtendo o ID do usuário autenticado
                var usuarioId = User
                    .Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)
                    ?.Value;

                if (int.TryParse(usuarioId, out int parsedUsuarioId))
                {
                    var novoPacote = new PacoteViewModel
                    {
                        Nome = pacote.Nome,
                        Origem = pacote.Origem,
                        Destino = pacote.Destino,
                        Atrativos = pacote.Atrativos,
                        Saida = pacote.Saida,
                        Retorno = pacote.Retorno,
                        UsuarioId = parsedUsuarioId
                    };

                    _context.Pacotes.Add(novoPacote);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("MenuUsuario", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Erro ao obter o ID do usuário.");
                }
            }
            return RedirectToAction("MenuUsuario", "Home", pacote);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<div class="container text-center d-flex justify-content-center align-items-center">
    <div class="d-flex justify-content-center align-items-center" id="menu-index">
        <div class="d-flex justify-content-around align-items-center" id="menu-index-btn-box">
            <div id="menu-index-btn-login">
                <button type="button" class="btn btn-light" id="btn-login" data-bs-toggle="modal"
                    data-bs-target="#modal-login">Login</button>
            </div>
            <div id="menu-index-btn-vitrine">
                <button type="button" class="btn btn-light" id="btn-vitrine"
                    onclick="window.location.href='@Url.Action("Vitrine", "Home")'">Vitrine</button>
            </div>

            @if (TempData["ErrorMessage"] != null && !string.IsNullOrEmpty(TempData["ErrorMessage"].ToString()))
            {
                <div class="alert alert-danger" role="alert" id="login-error-msg">
                    @TempData["ErrorMessage"]
                </div>
            }
        </div>
    </div>

    <div class="modal fade" id="modal-login" tabindex="-1" aria-labelledby="modal-loginLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" id="modal-dialog">
            <div class="modal-content d-flex justify-content-center align-items-center" id="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modal-loginLabel">Destino Certo - Login</h1>
                    <button type="button" class="btn-close ms-3" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal-body">
                    <form asp-controller="Login" asp-action="LoginUsuario" method="post">
                        <div>
                            <label class="form-label" for="login-input">Login</label>
                            <input class="form-control" type="text" id="login-input" name="Login" required>
                        </div>
                        <div>
                            <label class="form-label" for="senha-input">Senha</label>
                            <input class="form-control" type="password" id="senha-input" name="Senha" required>
                        </div>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Voltar</button>
                        <button type="submit" class="btn btn-primary">Log-in</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/MenuUsuario.cshtml
@{
    ViewData["Title"] = "Usuário";
}

<div class="container d-flex justify-content-center align-items-center">
    <div class="row" id="usuario-container">
        <div class="col-3" id="usuario-menu-lateral">
            <button class="usuario-menu-btn1 usuario-menu-btn2" id="usuario-menu-btn-adicionar">Adicionar</button>
            <button class="usuario-menu-btn1 usuario-menu-btn2" id="usuario-menu-btn-editar">Editar</button>
            <button class="usuario-menu-btn1 usuario-menu-btn2" id="usuario-menu-btn-listar">Listar</button>
            <button class="usuario-menu-btn1 usuario-menu-btn2" id="usuario-menu-btn-excluir">Excluir</button>
        </div>
        <div class="col-9" id="usuario-tela">

            <div id="usuario-menu-tela-adicionar">
                <h5 class="text-center mb-2">Adicionar pacote</h5>
                <div class="d-flex justify-content-center align-items-center">
                    <form method="post" id="form-usuario-adicionar" asp-action="AdicionarPacote" asp-controller="Pacotes">
                        <div class="mb-3 row">
                            <label for="nome" class="col-sm-2 col-form-label">Nome</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nome" name="nome" required>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="origem" class="col-sm-2 col-form-label">Origem</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="origem" name="origem" required>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="destino" class="col-sm-2 col-form-label">Destino</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="destino" name="destino" required>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="atrativos" class="col-sm-2 col-form-label">Atrativos</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" id="atrativos" name="atrativos" rows="3" required></textarea>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="saida" class="col-sm-2 col-form-label">Saída</label>
                            <div class="col-sm-10">
                                <input type="datetime-local" class="form-control" id="saida" name="saida" required>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="retorno" class="col-sm-2 col-form-label">Retorno</label>
                            <div class="col-sm-10">
                                <input type="datetime-local" class="form-control" id="retorno" name="retorno" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-10 offset-sm-2 text-end">
                                <button type="submit" class="btn btn-primary">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div id="usuario-menu-tela-editar">
                <h5 class="text-center mb-2">Editar pacote</h5>
                <div class="d-flex justify-content-center align-items-center">
                    <form method="post" id="form-usuario-editar">
                        <div class="mb-3 row">
                            <label for="nome" class="col-sm-2 col-form-label">Nome</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="nome" name="nome">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="origem" class="col-sm-2 col-form-label">Origem</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="origem" name="origem">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="destino" class="col-sm-2 col-form-label">Destino</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="destino" name="destino">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="atrativos" class="col-sm-2 col-form-label">Atrativos</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" id="atrativos" name="atrativos" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="saida" class="col-sm-2 col-form-label">Saída</label>
                            <div class="col-sm-10">
                                <input type="datetime-local" class="form-control" id="saida" name="saida">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="retorno" class="col-sm-2 col-form-label">Retorno</label>
                            <div class="col-sm-10">
                                <input type="datetime-local" class="form-control" id="retorno" name="retorno">
                            </div>
                        </div>
                    </form>

                    <form id="form-usuario-editar-anterior">
                        <fieldset class="m-0" disabled>
                            <div class="mb-3 row">
                                <div>
                                    <input type="text" class="form-control" id="nome" name="nome">
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <div>
                                    <input type="text" class="form-control" id="origem" name="origem">
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <div>
                                    <input type="text" class="form-control" id="destino" name="destino">
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <div>
                                    <textarea class="form-control" id="atrativos" name="atrativos" rows="3"></textarea>
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <div>
                                    <input type="datetime-local" class="form-control" id="saida" name="saida">
                                </div>
                            </div>
                            <div class="mb-3 row">
                                <div>
                                    <input type="datetime-local" class="form-control" id="retorno" name="retorno">
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
                <div class="me-3 text-end">
                    <button type="submit" class="btn btn-primary" id="form-usuario-editar-btn">Enviar</button>
                </div>
            </div>

            <div id="usuario-menu-tela-listar">
                <h5 class="text-center mb-2">Listar pacote(s)</h5>
                <div id="usuario-menu-listar-lista">
                    <table class="table">
                        <tbody>
                            @foreach(var pacote in ViewBag.Pacotes)
                            {
                                <div class="card mb-3">
                                <div class="row g-0">
                                    <div class="col-md-3" id="card-image">
                                        <img src="https://picsum.photos/200" class="img-fluid rounded-start">
                                    </div>
                                    <div class="col-md-8" id="card-content">
                                        <div class="position-absolute top-0 end-0 me-2" id="card-id ">
                                            Id: @pacote.Id
                                        </div>
                                        <div class="card-body" id="card-body">
                                            <h5 class="card-title text-center" id="card-title">@pacote.Nome</h5>
                                            <h6>Atrativos</h6>
                                            <p class="card-text" id="card-atrativos">@pacote.Atrativos</p>
                                            <div class="d-flex justify-content-around">
                                                <span id="card-origem">Origem: @pacote.Origem</span>
                                                <span id="card-destino">Destino: @pacote.Destino</span>
                                            </div>

                                            <div class="text-body-secondary d-flex justify-content-around">
                                                <span id="card-saida">@pacote.Saida.ToString("dd/MM/yyyy - HH:mm")</span>
                                                <span id="card-retorno">@pacote.Retorno.ToString("dd/MM/yyyy - HH:mm")</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div id="usuario-menu-tela-excluir">
                <h5 class="text-center mb-2">Excluir pacote(s)</h5>
                <div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Id</span>
                        <input type="number" class="form-control" placeholder="Digite o Id do pacote"
                            aria-describedby="basic-addon1">
                    </div>
                </div>

                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-3" id="card-image">
                            <img src="https://picsum.photos/200" class="img-fluid rounded-start">
                        </div>
                        <div class="col-md-8" id="card-content">
                            <div class="position-absolute top-0 end-0 me-2" id="card-id">
                                Id:
                            </div>
                            <div class="card-body" id="card-body">
                                <h5 class="card-title text-center" id="card-title">São Carlos</h5>
                                <h6>Atrativos</h6>
                                <p class="card-text" id="card-atrativos">Texto de atrativos aqui</p>
                                <div class="d-flex justify-content-around">
                                    <span id="card-origem">Origem: Araraquara/SP</span>
                                    <span id="card-destino">Destino: São Carlos/SP</span>
                                </div>

                                <div class="text-body-secondary d-flex justify-content-around">
                                    <span id="card-saida">dd/mm/yyyy - 00:00</span>
                                    <span id="card-retorno">dd/mm/yyyy - 00:00</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-center me-3">
                    <input type="checkbox" class="btn-check" id="menu-excluir-btn-check" autocomplete="off">
                    <label class="btn btn-outline-danger" for="menu-excluir-btn-check">Confirmar?</label><br>

                    <button class="usuario-menu-btn1 usuario-menu-btn2" id="btn-excluir">Excluir</button>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Home/TesteDb.cshtml
@{
    ViewData["Title"] = "Teste Db";
}

<div class="text-center">
    <h1 class="display-4">Usuários</h1>
    <ul>
        @foreach (var usuario in ViewBag.Usuarios)
        {
            <li>@usuario.Nome (@usuario.Login)</li>
        }
    </ul>

    <h1 class="display-4">Pacotes</h1>
    <ul>
        @foreach (var pacote in ViewBag.Pacotes)
        {
            <li>@pacote.Nome: @pacote.Origem -> @pacote.Destino (Saída: @pacote.Saida, Retorno: @pacote.Retorno)</li>
        }
    </ul>
</div>

Views/Home/Vitrine.cshtml
@{
  ViewData["Title"] = "Vitrine";
}

<div class="container d-flex justify-content-center">
  <div id="vitrine-container">
    <table class="table">
      <tbody>
        @foreach(var pacote in ViewBag.Pacotes)
        {
          <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-3" id="card-image">
              <img src="https://picsum.photos/200" class="img-fluid rounded-start">
            </div>
            <div class="col-md-8" id="card-content">
              <div class="card-body" id="card-body">
                <h5 class="card-title text-center" id="card-title">@pacote.Nome</h5>
                <h6>Atrativos</h6>
                <p class="card-text" id="card-atrativos">@pacote.Atrativos</p>
                <div class="d-flex justify-content-around">
                  <span id="card-origem">Origem: @pacote.Origem</span>
                  <span id="card-destino">Destino: @pacote.Destino</span>
                </div>

                <div class="text-body-secondary d-flex justify-content-around">
                  <span id="card-saida">@pacote.Saida.ToString("dd/MM/yyyy - HH:mm")</span>
                  <span id="card-retorno">@pacote.Retorno.ToString("dd/MM/yyyy - HH:mm")</span>
                </div>
              </div>            
            </div>
          </div>
        </div>
        }
      </tbody>
    </table>
  </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DestinoCertoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DestinoCertoMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DestinoCertoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>